language: java
jdk:
  - openjdk8

branches:
  only:
    - master

# Travis CI 서버의 home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

before_install:
  - chmod +x gradlew

before_deploy:
  - mkdir -p before-deploy # zip에 포함시킬 파일들을 담을 디렉토리 생성
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/
  - cd before-deploy && zip -r before-deploy # before-deploy로 이동 후 전체 압축
  - cd ../ && mkdir -p deploy # 상위 디렉토리로 이동 후 deploy 디렉토리 생성
  - mv before-deploy/before-deploy.zip deploy/jik-springboot2-webservice.zip # deploy로 zip파일 이동

deploy:
  - provider: s3
    wait_until_deployed: true
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: jik-springboot-build # s3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private으로
    local_dir: deploy # before_deploy에서 생성한 디렉토리

  - provider: codedeploy
    wait_until_deployed: true
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY # Travis repo settings에 설정된 값
    bucket: jik-springboot-build #S3 버킷
    key : jik-springboot2-webservice.zip # 빌드 파일을 압축해서 전달
    bundle_type: zip # 압축 확장자
    application: jik-springboot2-webservice # 웹 콘솔에서 등록한 Codedeploy 애플리케이션
    deployment_group: jik-springboot2-webservice-group # 웹 콘솔에서 등록한 CodeDeploy 배포 그룹
    region: ap-northeast-2

#CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - tsi03136@gmail.com